name: hair_again_staff_app
description: "Hair Again ERP — Staff Mobile App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.3
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
